/*
 * ARM Limited (ARM) is supplying this software for use with Cortex-M
 * processor based microcontroller, but can be equally used for other
 * suitable processor architectures. This file can be freely distributed.
 * Modifications to this file shall be clearly marked.
 * 
 * THIS SOFTWARE IS PROVIDED "AS IS". NO WARRANTIES, WHETHER EXPRESS, IMPLIED
 * OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.
 * ARM SHALL NOT, IN ANY CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL, OR
 * CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 * @file     GSMCU_M3.h
 * @brief    CMSIS HeaderFile
 * @version  1.2
 * @date     25. September 2017
 * @note     Generated by SVDConv V3.2.66 on Monday, 25.09.2017 10:11:35
 *           from File 'Meter_M0.svd',
 *           last modified on Monday, 25.09.2017 02:09:51
 */



/** @addtogroup xin
  * @{
  */


/** @addtogroup Meter_M0
  * @{
  */


#ifndef GSMCU_M3_H
#define GSMCU_M3_H

#ifdef __cplusplus
extern "C" {
#endif
	
#include <stdint.h>

#if defined(ZB204_CHIP)
#include "ZB204.h"
#elif defined(ZB205_CHIP)
#include "ZB205.h"
#elif defined(ZB206_CHIP)
#include "ZB206.h"   
#else
#endif

#ifdef __cplusplus
}
#endif

#endif /* gsmcu_m3_H */



